export const KEY_WORDS: string[] = [
    "sports nutrition supplements",
    "buy sports supplements online",
    "premium sports nutrition",
    "performance supplements USA",
    "fitness supplements store",
    "muscle building supplements",
    "workout supplements for men",
    "workout supplements for women",
    "dietary supplements USA",
    "best supplements for athletes",
    "gym supplements online",
    "strength training supplements",
    "supplements for muscle growth",
    "recovery supplements for athletes",
    "natural sports supplements",
    "clean supplements brand",
    "science backed supplements",
    "daily performance supplements",
    "high quality supplements USA",
    "buy supplements online USA",
    "creatine monohydrate",
    "pure creatine monohydrate",
    "micronized creatine monohydrate",
    "buy creatine monohydrate",
    "best creatine monohydrate",
    "creatine for muscle growth",
    "creatine for strength",
    "creatine for performance",
    "unflavored creatine powder",
    "creatine supplement USA",
    "creatine for men",
    "creatine for women",
    "creatine without fillers",
    "creatine for beginners",
    "creatine for weight training",
    "creatine for powerlifting",
    "daily creatine supplement",
    "creatine post workout",
    "pharmaceutical grade creatine",
    "creatine muscle recovery",
    "omega 3 supplement",
    "omega 3 fish oil",
    "high potency omega 3",
    "omega 3 capsules",
    "omega 3 for heart health",
    "omega 3 for brain health",
    "omega 3 for athletes",
    "purified fish oil supplement",
    "omega 3 EPA DHA",
    "buy omega 3 online",
    "best omega 3 supplement",
    "omega 3 daily dose",
    "omega 3 for inflammation",
    "omega 3 for recovery",
    "omega 3 softgels",
    "pharmaceutical grade fish oil",
    "omega 3 supplement USA",
    "omega 3 for joint health",
    "omega 3 for active lifestyle",
    "clean omega 3 supplement",
    "vitamin D3 K2 spray",
    "D3 K2 oral spray",
    "vitamin D3 with K2 MK7",
    "vitamin D3 K2 supplement",
    "D3 K2 for bone health",
    "D3 K2 for immune support",
    "best vitamin D3 K2",
    "D3 K2 spray USA",
    "liquid vitamin D3 K2",
    "D3 K2 daily supplement",
    "vitamin K2 MK7 supplement",
    "vitamin D3 spray for adults",
    "D3 K2 high potency",
    "D3 K2 for calcium absorption",
    "buy vitamin D3 K2 online",
    "D3 K2 immune support",
    "D3 K2 bone formula",
    "D3 K2 performance supplement",
    "vitamin D3 K2 drops",
    "clean D3 K2 supplement",
    "bone support supplement",
    "calcium supplement for bones",
    "calcium citrate supplement",
    "calcium bisglycinate supplement",
    "bone health formula",
    "calcium magnesium zinc supplement",
    "calcium D3 K2 supplement",
    "best calcium supplement",
    "calcium for adults",
    "bone strength supplement",
    "calcium supplement USA",
    "calcium with vitamin D3",
    "calcium with magnesium",
    "bone support formula USA",
    "high absorption calcium",
    "calcium for men",
    "calcium for women",
    "bone density support supplement",
    "daily calcium supplement",
    "calcium MK7 supplement",
    "natural test booster",
    "testosterone booster supplement",
    "test booster for men",
    "testosterone support supplement",
    "boost testosterone naturally",
    "test booster USA",
    "performance test booster",
    "strength test booster",
    "muscle growth test booster",
    "testosterone support formula",
    "natural testosterone enhancer",
    "men's vitality supplement",
    "testosterone booster capsules",
    "best test booster",
    "test booster for gym",
    "hormone support supplement",
    "testosterone optimization supplement",
    "male performance supplement",
    "daily test booster",
    "clean testosterone booster",
    "kids multivitamin",
    "children's vitamins",
    "vitamins for kids",
    "kids immune support vitamins",
    "vitamin D for kids",
    "omega 3 for kids",
    "kids daily vitamins",
    "children multivitamin supplement",
    "healthy growth vitamins",
    "kids bone support vitamins",
    "chewable kids vitamins",
    "liquid vitamins for kids",
    "natural kids vitamins",
    "kids vitamin spray",
    "children immune support",
    "best vitamins for kids",
    "sugar free kids vitamins",
    "kids health supplements",
    "pediatric multivitamin",
    "vitamins for active kids",
    "buy supplements USA",
    "online supplement store USA",
    "premium vitamin brand",
    "clean ingredient supplements",
    "high absorption vitamins",
    "performance nutrition USA",
    "muscle recovery supplements",
    "immune support supplements",
    "daily health supplements",
    "natural dietary supplements",
    "supplements for active lifestyle",
    "strength and endurance supplements",
    "supplements for gym performance",
    "muscle support supplements",
    "bone and joint supplements",
    "heart health supplements",
    "brain health supplements",
    "men's health supplements",
    "women's health supplements",
    "family vitamins and supplements",
    "where to buy creatine monohydrate online",
    "best creatine for muscle growth",
    "high quality omega 3 supplement",
    "vitamin D3 K2 spray USA",
    "calcium magnesium zinc for bones",
    "testosterone booster for muscle gain",
    "supplements for strength training",
    "creatine for beginners guide",
    "omega 3 for athletes recovery",
    "D3 K2 for calcium absorption",
    "best calcium supplement for adults",
    "bone support supplement with MK7",
    "immune support vitamins for adults",
    "muscle building supplements USA",
    "sports supplements for men",
    "sports supplements for women",
    "natural testosterone support USA",
    "omega 3 for heart and brain",
    "high potency vitamin D3 K2",
    "daily creatine supplement powder",
    "clean sports nutrition brand",
    "premium creatine powder USA",
    "high absorption calcium citrate",
    "kids immune vitamins USA",
    "pharmaceutical grade omega 3",
    "science based supplements brand",
    "supplements for muscle strength",
    "bone density support formula",
    "natural vitality supplements",
    "performance supplement brand USA",
    "buy vitamins online USA",
    "men's performance supplements",
    "women's wellness supplements",
    "advanced bone support formula",
    "strength and power supplements",
    "immune system support vitamins",
    "daily omega 3 capsules",
    "pure micronized creatine powder",
    "vitamin D3 K2 immune formula",
    "complete bone health supplement",
];
